CREATE SCHEMA `MCPUBS` ;

CREATE TABLE `MCPUBS`.`Pub` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fullCode` VARCHAR(70) NOT NULL COMMENT '',
  `rootCode` VARCHAR(10) NOT NULL COMMENT '',
  `code` INT NULL DEFAULT NULL COMMENT '',
  `version` VARCHAR(5) NULL DEFAULT NULL COMMENT '',
  `active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `title` TEXT NULL DEFAULT NULL COMMENT '',
  `readableTitle` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '');